version: '3.8'  

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - ./mage_data:/home/src
    depends_on:
      - postgres
    environment:
      MAGE_DATABASE_CONNECTION_URL: postgresql://username:password@postgres:5432/postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: