version: '3.9'

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    ports:
      - "6789:6789"
    environment:
      - MAGE_DATABASE_CONNECTION_URL=postgresql://mage:magepassword@postgres:5432/magedb
    volumes:
      - ./mage_data:/home/src
